const tables = [{id:1,capacity:2},{id:2,capacity:4},{id:3,capacity:2},{id:4,capacity:6},{id:5,capacity:4},{id:6,capacity:6}];
const state = { queue:[], running:false, served:0, reward:0, waits:[], episode:0, ticks:0, timer:null, clock:720, tables:tables.map(t=>({...t,status:'available',guests:0,clearAt:0})) };
const notes = { 'Q-Learning':'Balances exploration with the best known table allocation.', 'Expected SARSA':'Evaluates the expected reward across possible future actions.', 'Actor-Critic':'Uses a policy actor and value critic to select allocations.', 'DQN':'Approximates allocation values with replay-based learning.', 'N-Step Tree Backup':'Uses multi-step returns to strengthen policy estimates.', 'Best Fit (baseline)':'Always selects the smallest suitable available table.' };
const $ = id => document.getElementById(id);
function chooseTable(group) { const available=state.tables.filter(t=>t.status==='available'&&t.capacity>=group); if(!available.length)return null; const algorithm=$('algorithm').value; if(algorithm==='DQN'&&Math.random()<.18) return available[Math.floor(Math.random()*available.length)]; if(algorithm==='Actor-Critic'&&Math.random()<.12) return available[available.length-1]; return available.sort((a,b)=>(a.capacity-group)-(b.capacity-group)||a.id-b.id)[0]; }
function renderFloor(){ $('floor').innerHTML=state.tables.map(t=>`<article class="table ${t.status}"><header>TABLE ${t.id}</header><span class="capacity">${t.capacity} seats</span><span class="chairs"></span>${t.guests?`<span class="guest-count">${t.guests}</span>`:''}<span class="state">${t.status==='available'?'AVAILABLE':t.status==='occupied'?'IN SERVICE':'CLEARING'}</span></article>`).join(''); $('utilization').textContent=`${state.tables.filter(t=>t.status!=='available').length} / 6`; }
function renderQueue(){ const q=$('queue'); $('queueCount').textContent=`${state.queue.length} ${state.queue.length===1?'group':'groups'}`; q.className=`queue${state.queue.length?'':''}`; q.innerHTML=state.queue.length?state.queue.map((g,i)=>`<span class="group-chip">#${i+1} · ${g.size} ${g.size===1?'guest':'guests'}</span>`).join(''):'No customers waiting'; }
function updateMetrics(){ const avg=state.waits.length?state.waits.reduce((a,b)=>a+b,0)/state.waits.length:0; const confidence=Math.min(96,50+state.episode*3); $('served').textContent=state.served;$('waitTime').textContent=`${avg.toFixed(1)}m`;$('reward').textContent=state.reward;$('confidence').textContent=`${confidence}%`;$('episode').textContent=`Episode ${state.episode}`;$('progress').style.width=`${Math.min(100,state.episode*10)}%`; $('servedTrend').textContent=state.served?`${state.served} guests seated`:'Awaiting first allocation'; $('waitTrend').textContent=state.waits.length?'Lower is better':'No waiting data'; $('rewardTrend').textContent=state.served?`Per allocation: ${(state.reward/state.served).toFixed(1)}`:'Per allocation: —'; $('confidenceTrend').textContent=confidence>75?'Policy becoming stable':'Exploring options'; $('learningCopy').textContent=state.episode?`${$('algorithm').value} has updated from ${state.episode} service decisions.`:'Run a service to observe allocation decisions.'; }
function addGroup(size){ size=Number(size);if(!Number.isInteger(size)||size<1||size>6)return; state.queue.push({size,arrived:state.ticks});renderQueue(); $('decision').innerHTML=`<span class="robot">✦</span><div><strong>Group of ${size} joined the queue</strong><p>The agent will choose a suitable table when service starts.</p></div>`; }
function tick(){ state.ticks++;state.clock=(state.clock+3)%1440;const h=Math.floor(state.clock/60)%12||12,m=String(state.clock%60).padStart(2,'0');$('clock').textContent=`${h}:${m} ${state.clock<720?'AM':'PM'}`; state.tables.forEach(t=>{if(t.status==='occupied'&&t.clearAt<=state.ticks){t.status='cleaning';t.clearAt=state.ticks+1;}else if(t.status==='cleaning'&&t.clearAt<=state.ticks){t.status='available';t.guests=0;}}); if(state.queue.length){const group=state.queue[0],table=chooseTable(group.size);if(table){state.queue.shift();table.status='occupied';table.guests=group.size;table.clearAt=state.ticks+3+Math.floor(Math.random()*3);const waste=table.capacity-group.size,reward=Math.max(2,12-waste*2),wait=Math.max(.2,(state.ticks-group.arrived)*.4);state.served+=group.size;state.reward+=reward;state.waits.push(wait);state.episode++;$('decision').innerHTML=`<span class="robot">✦</span><div><strong>Allocated ${group.size} guests to Table ${table.id}</strong><p>${$('algorithm').value} chose a ${table.capacity}-seat table · reward +${reward}</p></div>`;}else {$('decision').innerHTML=`<span class="robot">✦</span><div><strong>All suitable tables are occupied</strong><p>The next group remains in the queue until a table is clear.</p></div>`;}}renderFloor();renderQueue();updateMetrics(); }
function toggle(){state.running=!state.running;$('start').textContent=state.running?'❚❚ Pause service':'▶ Start service';$('runState').textContent=state.running?'Service simulation running':'Simulation paused';if(state.running){tick();state.timer=setInterval(tick,1300)}else clearInterval(state.timer)}
function reset(){clearInterval(state.timer);Object.assign(state,{queue:[],running:false,served:0,reward:0,waits:[],episode:0,ticks:0,clock:720,tables:tables.map(t=>({...t,status:'available',guests:0,clearAt:0}))});$('start').textContent='▶ Start service';$('runState').textContent='Ready to simulate';$('clock').textContent='12:00 PM';$('decision').innerHTML='<span class="robot">✦</span><div><strong>RL agent ready</strong><p>Add a customer group, then start the service.</p></div>';renderFloor();renderQueue();updateMetrics();}
$('addGroup').onclick=()=>addGroup($('groupSize').value);document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>addGroup(b.dataset.size));$('start').onclick=toggle;$('reset').onclick=reset;$('algorithm').onchange=e=>{$('algorithmNote').textContent=notes[e.target.value];};document.addEventListener('keydown',e=>{if(e.code==='Space'&&e.target.tagName!=='INPUT'){e.preventDefault();toggle();}});renderFloor();renderQueue();updateMetrics();
